name: Feature workflow

on:
  push:
    branches:
      - 'feature/*'

jobs:

  unittests:
    name: Run tests
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.9.18, "3.10.13", 3.11.5, 3.12.0, 3.13.4]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unittests
        uses: ./.github/actions/unittests
        with:
          python-version: ${{ matrix.python-version }}
