name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Release Please"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success' &&
        startsWith(github.event.workflow_run.head_commit.message, 'chore(master): release')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
