name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  unittests:
    uses: ./.github/workflows/run-unittests.yml
    with:
      python-versions: '["3.9", "3.10", "3.11", "3.12"]'

  release-please:
    name: Release Please
    needs: unittests
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
